sysRevu/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

		
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'newProject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sysrev/', include('sysrev.urls')),
    url(r'^', include('sysrev.urls')),
   	#url(r'^accounts/',include('registration.backends.simple.urls')),
)
# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

sysrev/urls.py
from django.conf.urls import patterns, url
from sysrev import views

urlpatterns = patterns('',

    # Basic routes
    url(r'^$',          views.index,       name='index'),
    url(r'^about/$',    views.about,       name='about'),
    url(r'^register/$', views.register,    name='register'),
    url(r'^login/$',    views.user_login,  name='login'),
    url(r'^logout/$',   views.user_logout, name='logout'),

    # SysRev routes
    url(r'^dashboard/$',        views.dashboard,     name='dashboard'),
    url(r'^add_review/$',       views.add_review,    name='add_review'),
    url(r'^review/(\d+)/$',     views.review,        name='review'),
    url(r'^delete/(\d+)/$',     views.delete_review, name='delete_review'),
    url(r'^get_doc_count/$',    views.get_doc_count, name='get_doc_count'),
    url(r'^review/abstract/(\d+)/(\d+)/$', views.mark_abstract, name='mark_abstract'),
    url(r'^review/document/(\d+)/(\d+)/$', views.mark_document, name='mark_document'),
    url(r'^review/edit/(\d+)/$',           views.edit_review,   name='edit_review'),
    url(r'^review/done/(\d+)/(\S+)/$',     views.end_stage,     name='end_stage'),

    # Update profile routes
    url(r'^update_profile/$',  views.update_profile,  name='update_profile'),
    url(r'^update_password/$', views.update_password, name='update_password'),
    url(r'^update_email/$',    views.update_email,    name='update_email'),

)

sysrev/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime

# Models for SysRev

class Researcher(models.Model):

    # Link Researcher to Django User
    user = models.OneToOneField(User)

    # forename = models.CharField(max_length=100, null=True, blank=True)
    # surname = models.CharField(max_length=100, null=True, blank=True)

    def __unicode__(self):
        return self.user.username


class Review(models.Model):
    user            = models.ForeignKey(Researcher)
    title           = models.CharField(max_length=128)
    description     = models.CharField(max_length=128)
    date_started    = models.DateTimeField(default=timezone.now)
    query_string    = models.CharField(max_length=128)

    def __unicode__(self):
        return self.title


class Paper(models.Model):
    review          = models.ForeignKey(Review,default=None)
    pubmed_id       = models.IntegerField()
    title           = models.CharField(max_length=128, default="")
    authors         = models.CharField(max_length=128, default="")
    abstract        = models.CharField(max_length=4096, default="")
    paper_url       = models.URLField(null=True, blank=True, default=None)
    date            = models.DateTimeField(auto_now_add=True, blank=True, default=datetime.now)
    abstract_rev    = models.NullBooleanField(null=True,default=None)
    document_rev    = models.NullBooleanField(null=True,default=None)

    def __unicode__(self):
        return self.title


class Query(models.Model):
    review = models.ForeignKey(Review, null=True)
    string = models.CharField(max_length=128)

    def __unicode__(self):
        return self.review

sysrev/forms.py
from django import forms
from django.contrib.auth.models import User
from sysrev.models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ResearcherForm(forms.ModelForm):

    forename    = forms.CharField(required=True)
    surname     = forms.CharField(required=True)

    class Meta:
        model = Researcher
        fields = ('forename', 'surname')


# Model form for a new review
class ReviewForm(forms.ModelForm):
    title           = forms.CharField(required=True)
    description     = forms.CharField(required=True)
    query_string    = forms.CharField(required=True)

    class Meta:
        model = Review
        fields = ('title', 'description', 'query_string')

sysrev/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

from sysrev.forms import *
from sysrev.query_pubmed import *
from sysrev.progress import *


def index(request):
    # If the user is logged in - redirect to dashboard
    if request.user.username:
        return HttpResponseRedirect('/sysrev/dashboard/')

    return HttpResponseRedirect('/sysrev/login/')


def about(request):
    context_dict = {'boldmessage': "Hello from about bold"}

    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0

    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
        if (datetime.now() - last_visit_time).seconds > 5:
            count += 1
            reset_last_visit_time = True
    else:
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = count

    context_dict['visits'] = count

    return render(request, 'sysrev/about.html', context_dict)


def register(request):
    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = ResearcherForm(data=request.POST)

        # If the two forms are valid...
        username = request.POST.get('username')
        try:
            checkUser = User.objects.get(username=username)
            if checkUser:
                return render(request, 'registration/register.html',
                              {'user_form': user_form, 'profile_form': profile_form, 'register_error': True,
                               'error_type': 'The username is already taken'})
        except Exception as e:
            pass

        if user_form.is_valid() and profile_form.is_valid():

            password = request.POST.get('password')
            repeatPassword = request.POST.get('repeatPassword')
            email = request.POST.get('email')

            try:
                check_email = User.objects.get(email=email)
                if check_email:
                    return render(request, 'registration/register.html',
                                  {'user_form': user_form, 'profile_form': profile_form, 'register_error': True,
                                   'error_type': 'The email is already taken'})
            except Exception as v:
                None
            if (password != repeatPassword):
                return render(request, 'registration/register.html',
                              {'user_form': user_form, 'profile_form': profile_form, 'register_error': True,
                               'error_type': 'The passwords don\'t match'})


            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True


        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = ResearcherForm()

    # Render the template depending on the context.
    return render(request,
                  'registration/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    logged_in_error = False;
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
        # because the request.POST.get('<variable>') returns None, if the value does not exist,
        # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')


        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/sysrev/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your sysrev account is disabled.")
        else:
            logged_in_error = True
            # Bad login details were provided. So we can't log the user in.
            # print "Invalid login details: {0}, {1}".format(username, password)
            # return HttpResponseRedirect("/sysrev/login")
            return render(request, 'registration/login.html', {'logged_in_error': logged_in_error})

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'registration/login.html', {'logged_in_error': logged_in_error})


@login_required
def user_logout(request):
    # Use the login_required() decorator to ensure only those logged in can access the view.
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/sysrev/')


@login_required
def dashboard(request):
    context_dict = {}

    try:
        user = Researcher.objects.get(user__username=request.user.username)
    except:
        user = None;


    reviews = Review.objects.filter(user=user)

    context_dict['reviews'] = []

    for review in reviews:
        local_dict = {}
        local_dict['id'] = review.id
        local_dict['title'] = review.title
        local_dict['description'] = review.description
        local_dict['query_string'] = review.query_string

        local_dict['abstracts_done'] = get_progress(review, "abstract")
        local_dict['documents_done'] = get_progress(review, "document")

        context_dict['reviews'].append(local_dict)

    response = render(request, 'sysrev/dashboard.html', context_dict)

    return response


@login_required
def add_review(request):
    # Rename this to 'add_review' or 'create_review' when possible

    # Check if a new review is posted
    if request.method == 'POST':

        title = request.POST['title']
        description = request.POST['description']
        query_string = request.POST['query_string']

        user = User.objects.get(username=request.user)
        researcher = Researcher.objects.get(user=user)

        # Make a new Review and save it
        review = Review(
            user=researcher,
            title=title,
            description=description,
            query_string=query_string
        )
        review.save()

        # Query PubMed to get a list of paper IDs
        id_list = get_id_list(query_string)

        # Loop through each ID
        for id in id_list['Id']:

            paper = Paper(
                review=review,
                pubmed_id=id,
            )
            paper.save()
            print "Saved paper", id

        # Yay, it works up to here! Go back to main page
        return HttpResponseRedirect('/sysrev/')


    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'sysrev/add_review.html', {})


@login_required
def review(request, id):
    return_dict = {}

    # Try and find the review
    try:
        review = Review.objects.get(id=id)

templates/sysrev/Index.html
{% extends 'sysrev/base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block body_block %}
    <div class="page-header text-center">
        <h1>Welcome {{ user.username }}!</h1>
    </div>

    <a href="{% url 'add_category' %}" class="btn btn-success ">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add New Review
    </a>

    {% if message != None %}
        <span>{{ message }}</span>
    {% endif %}

    <div class="row placeholders">
        <div class="placeholder">
            <br/>
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Reviews</h3>
                </div>
            </div>

            {% if reviews %}
                <ul class="list-group">
                    {% for review in reviews %}
                        <!-- PROCESS BAR -->
                        <div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-warning" style="width: 10% ">10</div>
                                <div class="progress-bar progress-bar-success" style="width: 20%">20</div>
                                <div class="progress-bar progress-bar-danger" style="width: 10%">10</div>
                            </div>
                        </div>

                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2">{{ review.title }}</div>
                                <div class="col-xs-7">{{ review.description }}</div>
                                <div class="col-xs-1">{{ review.query_String }}</div>
                                <div class="col-xs-1"><a href="#" class="btn btn-default">Continue/View</a></div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no reviews present.</strong>
            {% endif %}
        </div>
    </div>


    <p> Visits: {{ visits }}</p>
{% endblock %}

templates/sysrev/add_category.html
{% extends 'sysrev/base.html' %}

{# Needed to load the script for retreiving document count #}
{% load staticfiles %}

{% block body_public %}
    <h1 class="page-header text-center">New Review</h1>

    <form class="form-signin" role="form" method="post" action="/sysrev/add_category/">
        {% csrf_token %}

        <input class="form-control" id="id_title" name="title" type="text" placeholder="Enter review title" required/><br/>
        <input class="form-control" id="id_query" name="query_string" type="text" placeholder="Enter query" required/><br/>
        <textarea class="form-control" rows="6" id="review_info" name="description" type="text" placeholder="Enter description of the review here" required></textarea><br/>


        <img id="loading-icon" src="{% static 'images/loading.gif' %}">
        <span id="document-count"></span>

        <br/><br/>

        <button type="submit" data-toggle="modal" data-target=".bs-example-modal-sm" class="btn btn-lg btn-success">Create</button>

        <a href="{% url 'index' %}" class="btn btn-lg btn-danger">Discard</a>

    </form>


<!-- Small modal -->

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <h3 id="please_wait_text">Please wait, your query is being processed.</h3> <br/>
        <img src="../../static/images/please_wait_loading.gif" id="please_wait_img">
    </div>
  </div>
</div>


    <script src = "{% static 'js/loading.js' %}"></script>
    <script src="{% static 'js/get_document_count.js' %}" ></script>

{% endblock %}

templates/sysrev/add_page.html
{% extends 'sysrev/base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}
{% if category %}

                <form role="form"  id="page_form" method="post" action="/sysrev/category/{{category.slug}}/add_page/">
            <h2 class="form-signin-heading">Add a Page to <a href="/sysrev/category/{{category.slug}}"> {{ category.name }}</a></h2>
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br/>
                        {{ field }}<br/>
                    {% endfor %}

                <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
                </form>
            {%  else %}
            <p>This is category does not exist.</p>
        {%  endif %}


        {% endblock %}

templates/sysrev/add_review.html
{% extends 'sysrev/base.html' %}

{# Needed to load the script for retreiving document count #}
{% load staticfiles %}

{% block body_block %}
    <h1 class="page-header text-center">New Review</h1>

    <form class="form-signin"  method="post" action="{% url 'add_review' %}">
        {% csrf_token %}

        <input class="form-control" id="id_title" name="title" type="text" placeholder="Enter review title" required/><br/>

        <input class="form-control" id="id_query" name="query_string" type="text" placeholder="Enter query" required/><br/>


        <div class="btn-block" id="advaned_button_div">
        <button type="button" id="advanced" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Advanced</button><br/>
        </div><br/>
        
        <textarea class="form-control" rows="6" id="review_info" name="description" placeholder="Enter description of the review here" required></textarea><br/>


        <img id="loading-icon" src="{% static 'images/loading.gif' %}" alt="Loading...">
        <span id="document-count"></span>

        <br/><br/>
        <div id="keep_discard_buttons">
        <button type="submit"  class="btn btn-lg btn-success"  id="create_button">Create</button>

        <a href="{% url 'index' %}" class="btn btn-lg btn-danger">Discard</a>
        </div>

    </form>

<!-- Large modal for advanced query interface -->

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <h3 id="advanced_query_title">Advanced Query Builder</h3> <br/>

        <div class="readability_score">
            <!--<div class="col-sm-6">Readability</div>-->
            <div class="input-group input-group-sm mtb10">

              <span class="input-group-addon" >
                          <div class="sb_line">
                                <select id="not_selector">
                                    <option value=" " label=" "></option>
                                    <option value="NOT" label="NOT">NOT</option>
                                </select>

                          </div>

              </span>
              <p><input class="form-control" id="id_query_modal" name="query_string_advanced" type="text" placeholder="Enter advanced query" required /></p><br/>
              <span class="input-group-addon ">
                  <!--<div class="sb_line">-->
                        <select id="and_or_selector">
                            <option value="AND" label="AND">AND</option>
                            <option value="OR" label="OR">OR</option>
                        </select>

                  <!--</div>-->

              </span>
              <span class="input-group-addon">

                        <button id="button_add_new_row"><i class="glyphicon glyphicon-plus"></i></button>


              </span>
            </div>
          </div>

        <div class="list" id="advanced_query_string_show"></div>

        <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="save_button" >Save</button>
        </div>

    </div>
  </div>
</div>


<!-- Small modal for creating a new review -->

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <h3 id="please_wait_text">Please wait, your query is being processed.</h3> <br/>
        <img src="../../static/images/please_wait_loading.gif" id="please_wait_img" alt="Please wait, your query is being processed...">
    </div>
  </div>
</div>

    <script src="{% static 'js/create_button_popup.js' %}"></script>
    <script src="{% static 'js/add_review_advanced_search_add_another_row.js' %}"></script>
    <script src = "{% static 'js/loading.js' %}"></script>
    <script src="{% static 'js/get_document_count.js' %}" ></script>

{% endblock %}

templates/sysrev/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../static/images/logo.jpg">

    <title>Systematic Review - {% block title %}{% endblock %}</title>

    <link href="https://bootswatch.com/readable/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">

    <!-- Load jQuery here so that later scripts can use $ -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

    <!-- Project stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <img class="navbar-brand" src="{% static "images/logo.jpg" %}" alt="logo"/>
            <a class="navbar-brand" href="/sysrev/">Systematic Reviews</a>
        </div>
        {% if user.is_authenticated %}
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/sysrev/update_profile">Update Profile</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
					<li><a href="/sysrev/logout">LogOut</a></li>
                </ul>
            </div>
        {% endif %}
    </div>
</div>

{% block body_public %}{% endblock %}
{% if user.is_authenticated %}

    <div class="jumbotron"><div class="container">
        {% block body_block %}{% endblock %}
    </div></div>



{% else %}
    {% block login_block %}
		<br/><br/><h4 class="text-center">Please <a href="/sysrev/login">log in</a> to use the app.</h4>
    {% endblock %}
{% endif %}

<div class="container">
    <p class="muted credit" id="footer_text">©2016 Systematic Review. All rights reserved.</p>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/sysrev/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        <li><a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}
	{% for c in cats %}
		{% if c == act_cat %} 
			<li  class="active" > 
		{% else  %} 
			<li>
		{% endif %}
		
		<a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>
	
	{% endfor %}

{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

templates/sysrev/edit_review.html
{% extends 'sysrev/base.html' %}

{# Needed to load the script for retreiving document count #}
{% load staticfiles %}

{% block body_block %}
    <h1 class="page-header text-center">Edit Review</h1>

    <form class="form-signin" method="post" action="/sysrev/review/edit/{{ review.id }}/">
        {% csrf_token %}

        <input class="form-control" id="id_title" name="title" type="text" placeholder="Enter review title" required value="{{ review.title }}"/><br/>
        <input class="form-control" id="id_query" name="query_string" type="text" placeholder="Enter query" required value="{{ review.query_string }}"/><br/>
        <textarea class="form-control" rows="6" id="review_info" name="description" placeholder="Enter description of the review here" required >{{ review.description }}</textarea><br/>


        <img id="loading-icon" src="{% static 'images/loading.gif' %}" alt="Getting Document Count...">
        <span id="document-count"></span>

        <br/>
        <div  id = "previous_queries">
        {% if queries %}
            <h5>List of previous queries:</h5>
            <ul>
                {% for query in queries %}
                    <li>{{ query.string }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        </div>

        <br/>
        <blockquote id="stylish_blockquote">
            <div class="container">
            <p id="warning_text">Editing the query may result in the deletion of some documents that have not been checked.</p>
            </div>
        </blockquote>

        <br />

        <div id="modify_discard_changes">
        <button type="submit" data-toggle="modal" data-target=".bs-example-modal-sm" class="btn btn-lg btn-success">Modify</button>
        <a href="/sysrev/review/{{ review.id }}" class="btn btn-lg btn-danger">Discard Changes</a>
            </div>

    </form>


<!-- Small modal -->

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <h3 id="please_wait_text">Please wait, your query is being processed.</h3> <br/>
        <img src="{% static 'images/please_wait_loading.gif' %}" id="please_wait_img" alt="Please Wait, Loading...">
    </div>
  </div>
</div>


    <script src = "{% static 'js/loading.js' %}"></script>
    <script src="{% static 'js/get_document_count.js' %}" ></script>

{% endblock %}

templates/sysrev/final.html
{% extends 'sysrev/base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <div class="page-header text-center">
        <h1 class="text-center">Final</h1>
    </div>

    <!--PAGINATATION -->
    <div>
        <nav>
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

    <div>
        <button type="submit" class="btn btn-success">Keep</button>
        <button type="submit" class="btn btn-danger">Discard</button>
    </div>


    <h2>Document Details& Title or link??</h2>

{% endblock %}

templates/sysrev/register.html
<!-- TO BE REMOVED ------------  USED FROM REGISTRATION FOLDER -->

<!--
{% extends 'sysrev/base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
        <h1>Register with Rango</h1>

        {% if registered %}
			Rango says: <strong>thank you for registering!</strong>
			<a href="/sysrev/">Return to the homepage.</a><br />
		{% else %}
			Rango says: <strong>register here!</strong><br />

			<form id="user_form" method="post" action="/sysrev/register/" enctype="multipart/form-data">

				{% csrf_token %}

				<!-- Display each form. The as_p method wraps each element in a paragraph
					 (<p>) element. This ensures each element appears on a new line,
					 making everything look neater. ->
				{{ user_form.as_p }}
				{{ profile_form.as_p }}

				<!-- Provide a button to click to submit the form. ->
				<input type="submit" name="submit" value="Register" />
			</form>
        {% endif %}

{% endblock %}
-->